platform :ios, '8.0'
pod 'AFNetworking'
#pod 'TSNetworkingSwift', :git => 'https://github.com/timsawtell/TSNetworkingSwift.git'
pod 'FFCircularProgressView', :git => 'https://github.com/timsawtell/FFCircularProgressView'
link_with 'TSBoilerplateSwift', 'TSBoilerplateSwiftTests'
